config/routes.rb
Stack::Application.routes.draw do
  resources :ambassadors

  resources :tests
  resources :questions

  get 'vote_on_features/overview'

  get 'questions/pull' => 'questions#pull'
  resources :stats

  devise_for :users

  root 'stats#index'

end

app/models/ambassador.rb
class Ambassador
  include Mongoid::Document
  field :Name,              type: String
  field :Stack_Username,    type: String
  field :Total,             type: Integer

def stacktotal
  Ambassador.update_attribute(:Total, "#{Question.where(:'answers.owner.display_name' => a.Stack_Username).count}")
end

end

app/controllers/ambassadors_controller.rb
class AmbassadorsController < ApplicationController
  before_action :set_ambassador, only: [:show, :edit, :update, :destroy]

  # GET /ambassadors
  # GET /ambassadors.json
  def index
    @ambassadors = Ambassador.all

    #@stackcontrib = Question.where(:'answers.owner.display_name' => "#{@ambassadors.each {|u| u.Stack_Username}}")

  end

  # GET /ambassadors/1
  # GET /ambassadors/1.json
  def show
  end

  # GET /ambassadors/new
  def new
    @ambassador = Ambassador.new
  end

  # GET /ambassadors/1/edit
  def edit
  end

  # POST /ambassadors
  # POST /ambassadors.json
  def create
    @ambassador = Ambassador.new(ambassador_params)

    respond_to do |format|
      if @ambassador.save
        format.html { redirect_to @ambassador, notice: 'Ambassador was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ambassador }
      else
        format.html { render action: 'new' }
        format.json { render json: @ambassador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ambassadors/1
  # PATCH/PUT /ambassadors/1.json
  def update
    respond_to do |format|
      if @ambassador.update(ambassador_params)
        format.html { redirect_to @ambassador, notice: 'Ambassador was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ambassador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ambassadors/1
  # DELETE /ambassadors/1.json
  def destroy
    @ambassador.destroy
    respond_to do |format|
      format.html { redirect_to ambassadors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ambassador
      @ambassador = Ambassador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ambassador_params
      params.require(:ambassador).permit(:Name, :Stack_Username)
    end
end

app/helpers/ambassador_helper.rb
module AmbassadorHelper
end

app/helpers/ambassadors_helper.rb
module AmbassadorsHelper
end

app/views/ambassadors/_form.html.haml
= form_for @ambassador do |f|
  - if @ambassador.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ambassador.errors.count, "error")} prohibited this ambassador from being saved:"
      %ul
        - @ambassador.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :Name
    = f.text_field :Name
  .field
    = f.label :Stack_Username
    = f.text_field :Stack_Username
  .actions
    = f.submit 'Save'

app/views/ambassadors/edit.html.haml
%h1 Editing ambassador

= render 'form'

= link_to 'Show', @ambassador
\|
= link_to 'Back', ambassadors_path

app/views/ambassadors/index.html.haml
%h1 Listing ambassadors
  
%table.table.table-striped
  %tr
    %th Name
    %th Stack username
    %th Stack Answers
    %th
    %th
  %tr
    %th User1
    %th StackUser1
    %th 4
  %tr
    %th User2
    %th StackUser2
    %th 9
  %tr
    %th User3
    %th StackUser3
    %th 19
  %tr
    %th User4
    %th StackUser4
    %th 2
  -# - Ambassador.stackcontrib.each do |ambassador|
  -#   %tr
  -#     %td= ambassador.name
  -#     %td= ambassador.username
  -#     %td= ambassador.count
  -#     %td= link_to 'Show', ambassador
  -#     %td= link_to 'Edit', edit_ambassador_path(ambassador)
  -#     %td= link_to 'Destroy', ambassador, :method => :delete, :data => { :confirm => 'Are you sure?' }
  
%br

= link_to 'New Ambassador', new_ambassador_path

app/views/ambassadors/new.html.haml
%h1 New ambassador

= render 'form'

= link_to 'Back', ambassadors_path

app/views/ambassadors/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @ambassador.Name
%p
  %b Stack username:
  = @ambassador.Stack_Username

= link_to 'Edit', edit_ambassador_path(@ambassador)
\|
= link_to 'Back', ambassadors_path