config/routes.rb
Stack::Application.routes.draw do
  resources :ambassadors

  resources :tests
  resources :questions

  get 'vote_on_features/overview'

  get 'questions/pull' => 'questions#pull'
  resources :stats

  devise_for :users

  root 'stats#index'

end

app/models/stat.rb
class Stat
  include Mongoid::Document
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :set_stat, only: [:show, :edit, :update, :destroy]
  require 'groupdate'

  # GET /stats
  # GET /stats.json
  def index
    blacklist = ["openshift"]
    @stats = Stat.all

    tags = Question.tags.flatten
    scrubbed = tags - blacklist

    @tag_sort = scrubbed.group_by{|i| i}.map{|k,v| [k, v.count] }.sort_by {|k,v| v}.reverse.first(10)

    @byweek = Question.week.map do |row|
      ["#{row["_id"]}", "#{row["value"]["count"].to_i}"]
    end

  end
  # GET /stats/1
  # GET /stats/1.json
  def show
  end

  # GET /stats/new
  def new
    @stat = Stat.new
  end

  # GET /stats/1/edit
  def edit
  end

  # POST /stats
  # POST /stats.json
  def create
    @stat = Stat.new(stat_params)

    respond_to do |format|
      if @stat.save
        format.html { redirect_to @stat, notice: 'Stat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stat }
      else
        format.html { render action: 'new' }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stats/1
  # PATCH/PUT /stats/1.json
  def update
    respond_to do |format|
      if @stat.update(stat_params)
        format.html { redirect_to @stat, notice: 'Stat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats/1
  # DELETE /stats/1.json
  def destroy
    @stat.destroy
    respond_to do |format|
      format.html { redirect_to stats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stat
      @stat = Stat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stat_params
      params[:stat]
    end
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/_form.html.haml
= form_for @stat do |f|
  - if @stat.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stat.errors.count, "error")} prohibited this stat from being saved:"
      %ul
        - @stat.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/stats/edit.html.haml
%h1 Editing stat

= render 'form'

= link_to 'Show', @stat
\|
= link_to 'Back', stats_path

app/views/stats/new.html.haml
%h1 New stat

= render 'form'

= link_to 'Back', stats_path

app/views/stats/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path